######################################################################
# Automatically generated by qmake (2.01a) Mon 7. Jun 08:20:39 2010
######################################################################

TEMPLATE = app
TARGET = drmencryptor
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drmencryptor.h
FORMS += drmencryptor.ui
SOURCES += drmencyptor.cpp main.cpp
LIBS += -lplatformenv -ldrmserviceapi -ldcfrep -ldrmparsers -lfbscli -lcone -lestor -lcaf